language: java
jdk:
  - oraclejdk8
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_failure:
  - cat target/surefire-reports/*.txt
notifications:
  email:
    recipients:
      - marek@switajski.de