language: java
jdk:
- oraclejdk8
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
after_failure:
- cat target/surefire-reports/*.txt
deploy:
  provider: releases
  api_key:
    secure: nj3A945ASt1Mt4NrxKgo4g/Wwwe+ImiheRBoTm/sudXTeza/mxLVMPZVJc7godr47F0cSc1PMxPqq3EiACMfchFMZdKz3AY2BSDwHDk5+hijMmS7f2+hQtc+NM2VXoiwjF8x7XAo5ciEpvLTOJd23XE2gA5xHbrV6iIpNfx0LOz2QqrypyR+pmgjD0cuaczl4Ad0T7wq9STMrjK17xYuWcZpVmAgeXNlz0G+Sv7GMJUJ0rL4/o0vdeMy74uFNH9un4aDE9TKVOVuqkCgPvgrt7yKNSfIcgqQfT/qIIFLZSTsB88PxkDZ2jF4iUsmDXoPLn226YJVs7Cnk3O3sV4i6ezmeo3ol631sdyNypKGHMo4lDz2yYeWUQokeHz2Mk5TEX5qE8vP8IICQH+aLnnt0XT8B/bBBKCYO5whHmRJBT7MmvQkFoVaSyM9N9QSCDxlKIwcUCO2aWjbT5sERnEPqRHIrzG8uCxR3Z+euG/6JojJzjNBGjc58SssNx/jjQsijRAVLlA8S/oQw93KGorE8FGGfJFTYVATVje0KELIPX7GKialz0RVPtQ4OU+30vmgvPX0gJqCtgw7XQsItRd+VvcWsLA3tkhTtRxGxDh14uPr7Em6PKYjZfdV+VTgdChKExufZCAaDbNrPnjyWteWAkiAnFArrHYnW67K4f1VL08=
  file: FlexibleOrders-0.1.0.BUILD-SNAPSHOT.war
  on:
    repo: Switajski/FlexibleOrders
