/*
 * File: app/store/BestellpositionDataStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.BestellpositionDataStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.BestellpositionData'
    ],

    reload: function(activeBestellnr){
    	this.load({
            params: {
                orderNumber: activeBestellnr
            },
            url: '/FlexibleOrders/orderitems/json/'
        });
    },
    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'MyApp.model.BestellpositionData',
            storeId: 'BestellpositionDataStore',
            proxy: {
                type: 'ajax',
                actionMethods: {
                    read: 'GET',
                    update: 'PUT',
                    destroy: 'DELETE',
                    create: 'POST'
                },
                api:{
                    read: '/FlexibleOrders/orderitems/json',
                    update: '/FlexibleOrders/orderitems/json',
                    destroy: '/FlexibleOrders/orderitems/json',
                    create: '/FlexibleOrders/orderitems/json'
                },
                headers: {
                    Accept: 'application/json'
                },
                reader: {
                    type: 'json',
                    successProperty: 'success',
                    root: 'data',
                    messageProperty: 'message'
                },
                autoSync: true,
                afterRequest:function(request,success){
                    console.log(request);	                    
                },
                listeners: {
                    exception: function(proxy, response, operation){
                        Ext.MessageBox.show({
                            title: 'Server Fehler',
                            msg: operation.getError(),
                            icon: Ext.MessageBox.ERROR,
                            buttons: Ext.Msg.OK
                        });
                    }
                }
                /*,
                filters: {
                    property: 'status',
                    value: {
                        Bestellung: 'NICHTBESTAETIGT'
                    }
                }  */
                
            }
        }, cfg)]);
    }
});