/*
 * File: app/store/BestellungDataStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.BestellungDataStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.BestellungData'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.BestellungData',
            storeId: 'BestellungDataStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                headers: {
                    Accept: 'application/json'
                },
                actionMethods: {
                    read: 'GET',
                    update: 'PUT',
                    destroy: 'DELETE',
                    create: 'POST'
                },
                api:{
                    read: '/leanorders/bestellungs',
                    update: '/leanorders/bestellungs',
                    destroy: '/leanorders/bestellungs',
                    create: '/leanorders/bestellungs'
                },
                reader: {
                    type: 'json',
                    successProperty: 'success',
                    root: 'data',
                    messageProperty: 'message'
                },
                autoSync: true,
                writer: {
                    type: 'json',
                    root: 'data',
                    writeAllFields: false
                }/*,
                afterRequest:function(request,success){
                    if(request.action = 'create'){
                    	console.log('create abfangen');
                    	console.log(request);
                    }                    
                },*/
            },
                listeners: {
                    exception: function(proxy, response, operation){
                        Ext.MessageBox.show({
                            title: 'Server Fehler',
                            msg: operation.getError(),
                            icon: Ext.MessageBox.ERROR,
                            buttons: Ext.Msg.OK
                        });
                    }           
            }
        }, cfg)]);
    }
});