/*
 * File: app/store/KundeDataStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.KundeDataStore', {
    extend: 'Ext.data.Store',
    customurl: '/FlexibleOrders/customers/json',
    requires: [
        'MyApp.model.KundeData'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.KundeData',
            storeId: 'KundeDataStore',
            pageSize: 1000,
            proxy: {
                type: 'ajax',
                url: '/FlexibleOrders/customers/json',
                headers: {
                    accept: 'application/json'
                },
                reader: {
                    type: 'json',
                    root: 'data'
                },
                api:{
                    read: this.customurl,
                    update: this.customurl,
                    destroy: this.customurl,
                    create: "/FlexibleOrders/customers/create"
                },
                writer : {
                	type: 'json',
                	allowSingle: true,
                	root: 'data'
                }
            }
        }, cfg)]);
    }
});