/*
 * File: app/view/BestellungWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BestellungWindow', {
    extend: 'Ext.window.Window',
    //height: 500,
    id: 'BestellungWindow',
    //width: 400,
    closeAction: 'hide',
    title: 'Bestellung',
    layout: {
        align: 'stretch',
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'BestellungForm',
                    layout: {
                        align: 'stretch',
                        type: 'fit'
                    },
                    bodyPadding: 10,
                    items:[
                        {
                            xtype: 'fieldset',
                            title: 'Bestellungdetails',
                            layout: {
                                align: 'stretch',
                                type: 'anchor'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'id',
                                    fieldLabel: 'Id'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'kunde',
                                    fieldLabel: 'Kunde'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'kundenhinweise',
                                    fieldLabel: 'Kundenhinweise'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'eigeneNotizen',
                                    fieldLabel: 'Eigene Notizen'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'status',
                                    fieldLabel: 'Status'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'bestelldatum',
                                    fieldLabel: 'Bestelldatum'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});