/*
 * File: app/view/BestellungWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BpWindow', {
    extend: 'Ext.window.Window',
    id: 'BpWindow',
    closeAction: 'hide',
    title: 'Bestellposition',
    layout: {
        align: 'stretch',
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'BpForm',
                    layout: {
                        align: 'stretch',
                        type: 'fit'
                    },
                    bodyPadding: 10,
                    items:[
                        {
                            xtype: 'fieldset',
                            title: 'Bestellpositionendetails',
                            layout: {
                                align: 'stretch',
                                type: 'anchor'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'id',
                                    fieldLabel: 'Id'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'bestellung',
                                    fieldLabel: 'Bestellung'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'rechnung',
                                    fieldLabel: 'Rechnung'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'auftragsbestaetigung',
                                    fieldLabel: 'auftragsbestaetigung'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'menge',
                                    fieldLabel: 'menge'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'preisNetto',
                                    fieldLabel: 'preisNetto'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'menge',
                                    fieldLabel: 'menge'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'status',
                                    fieldLabel: 'status'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'geteilt',
                                    fieldLabel: 'geteilt'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'anNaeherei',
                                    fieldLabel: 'anNaeherei'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'auslieferungsdatum',
                                    fieldLabel: 'auslieferungsdatum'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    name: 'geplantAusliefdatum',
                                    fieldLabel: 'geplantAusliefdatum'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});