/*
 * File: app/view/ErstelleBpWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ErstelleBpWindow', {
    extend: 'Ext.window.Window',
    id: 'ErstelleBpWindow',
    width: 400,
    layout: {
        align: 'stretch',
        type: 'fit'
    },
    closeAction: 'hide',
    title: 'Erstelle Bestellposition',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    id: 'ErstelleBpForm',
                    dock: 'top',
                    layout: {
                        align: 'stretch',
                        type: 'anchor'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            name: 'bestellung',
                            fieldLabel: 'Bestellung',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            anchor:'100%',
                            name:'artikel',
                            fieldLabel: 'Artikel',
                            allowBlank: false,
                            displayField: 'name',
                            valueField: 'artikelnummer',
                            enableRegEx: true,
                            forceSelection: true,
                            queryMode: 'local',
                            store: 'ArtikelDataStore',
                            tpl: Ext.create('Ext.XTemplate',
                                '<tpl for=".">',
                                '<div class="x-boundlist-item">{artikelnummer} - {name}</div>',
                                '</tpl>'
                            ),
                            displayTpl: Ext.create('Ext.XTemplate',
                                '<tpl for=".">',
                                '{artikelnummer} - {name}',
                                '</tpl>'
                            )
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Menge',
                            name:'menge',
                            allowBlank: false,
                            allowDecimals: false,
                            allowExponential: false,
                            minValue: 1
                        },
                        {
                            xtype: 'numberfield',
                            name: 'preisNetto',
                            fieldLabel: 'preisNetto',
                            allowBlank:true,
                            minValue: 1
                        },
                        {
                            xtype: 'checkboxfield',
                            fieldLabel: 'An N&auml;herei',
                            name: 'anNaeherei',
                            boxLabel: 'senden'
                        },
                        {
                            xtype: 'datefield',
                            format: "d/m/Y",
                            name: 'geplantAusliefdatum',
                            fieldLabel: 'geplantAusliefdatum'
                        }
                    ],
                    buttons: [{
                        text: 'Speichern',
                        formBind: true, //only enabled once the form is valid
                        disabled: true,
                        id: 'SubmitBpButton'
                    }]
                }
            ]
        });

        me.callParent(arguments);
    }

});