/*
 * File: app/view/ErstelleBestellungWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ErstelleBestellungWindow', {
    extend: 'Ext.window.Window',
    id: 'ErstelleBestellungWindow',
    width: 400,
    layout: {
        align: 'stretch',
        type: 'fit'
    },
    closeAction: 'hide',
    title: 'Erstelle Bestellung',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'form',
                    id: 'ErstelleBestellungForm',
                    dock: 'top',
                    layout: {
                        align: 'stretch',
                        type: 'anchor'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor:'100%',
                            name:'kunde',
                            fieldLabel: 'Kunde',
                            allowBlank: false,
                            displayField: 'name',
                            valueField: 'kundennummer',
                            enableRegEx: true,
                            forceSelection: true,
                            queryMode: 'local',
                            store: 'KundeDataStore',
                            tpl: Ext.create('Ext.XTemplate',
                                '<tpl for=".">',
                                '<div class="x-boundlist-item">{kundennummer} - {nachname}</div>',
                                '</tpl>'
                            ),
                            displayTpl: Ext.create('Ext.XTemplate',
                                '<tpl for=".">',
                                '{kundennummer} - {nachname}',
                                '</tpl>'
                            )
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Notizen',
                            name:'eigeneNotizen',
                            valueField:'eigeneNotizen'
                        }
                    ],
                    buttons: [{
                        text: 'Speichern',
                        formBind: true, //only enabled once the form is valid
                        disabled: true,
                        id: 'SubmitBestellungButton'
                    }]
                }
            ]
        });

        me.callParent(arguments);
    }

});