/*
 * File: app/view/MainPanel.js
 * 
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 * 
 * This file requires use of the Ext JS 4.2.x library, under independent
 * license. License of Sencha Architect does not include license for Ext JS
 * 4.2.x. For more details see http://www.sencha.com/license or contact
 * license@sencha.com.
 * 
 * This file will be auto-generated each and everytime you save your project.
 * 
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainPanel', {
	extend : 'Ext.panel.Panel',
	frame : false,
	height : 850,
	width : 1000,
	layout : {
		align : 'stretch',
		type : 'vbox'
	},
	title : 'Stand der Bestellungen',
	requires : ['MyApp.store.BestellpositionDataStore'],
	dockedItems : [{
		xtype : 'toolbar',
		dock : 'top',
		items : [{
			xtype : 'button',
			text : 'Berichte',
			icon : 'images/pdf_button.png',
			menu : {
				xtype : 'menu',
				minWidth : 120,
				items : [{

							id : 'showOrderedButton',
							icon : 'images/add.png',
							text : 'nicht best&auml;tigte Bestellpositionen anzeigen',
							scope : this
						}, {

							id : 'showConfirmedButton',
							icon : 'images/add.png',
							text : 'nicht gelieferte Auftragspositionen anzeigen',
							scope : this
						}, {

							id : 'showShippedButton',
							icon : 'images/add.png',
							text : 'nicht bezahlte Lieferungpositionen anzeigen',
							scope : this
						}, {

							id : 'showCompletedButton',
							icon : 'images/add.png',
							text : 'bezahlte/archivierte Positionen anzeigen',
							scope : this
						}, {
							xtype : 'menuseparator'
						}]
			}
		}, {
			xtype : 'button',
			text : 'Transaktionen',
			icon : 'images/pdf_button.png',
			menu : {
				xtype : 'menu',
				minWidth : 120,
				items : [{
							id : 'BestellungPdf',
							xtype : 'menuitem',
							text : 'erstelle Bestellungen'
						}, {
							id : 'AbPdf',
							xtype : 'menuitem',
							text : 'best&auml;tige'
						}, {
							id : 'RechnungPdf',
							xtype : 'menuitem',
							text : 'liefere'
						}, {
							id : 'OffeneBpPdf',
							xtype : 'menuitem',
							text : 'archiviere'
						}, {
							xtype : 'menuseparator'
						}]
			}

		}]

	}],

	initComponent : function() {
		var me = this;

		Ext.applyIf(me, {
			items : [{
				xtype : 'fieldcontainer',
				items : [{
							xtype : 'customercombobox',
							id : 'mainCustomerComboBox'
						}, {
							xtype : 'OrderItemGrid',
							store : 'BestellpositionDataStore',
							customurl : '/FlexibleOrders/customers/json/getItems',
							extraParams : {
								customer : 1,
								itemType : 'ordered'
							}
						}, {
							xtype : 'ShippingItemGrid',
							store : 'ShippingItemDataStore'
						}, {
							xtype : 'InvoiceItemGrid',
							store : 'InvoiceItemDataStore'
						}, {
							xtype : 'ArchiveItemGrid',
							store : 'ArchiveItemDataStore'
						}

				]
			}]
				// { xtype:'bestellunggridpanel' },

		});
		me.callParent(arguments);
	}
});