/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'MyApp.view.ErstelleBpWindow'
    ],

    frame: true,
    height: 500,
    width: 750,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Bestellungen',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 2,
                    id: 'BestellungGridPanel',
                    store: 'BestellungDataStore',
                    emptyText: 'Keine Bestellungen gefunden',
                    viewConfig: {
                        id: 'BestellungGrid'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'orderNumber',
                            text: 'Bestellnr'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'customer',
                            text: 'Kunde'
                        },
                        {
                        	xtype: 'gridcolumn',
                        	dataIndex: 'created',
                        	text: 'Bestelldatum'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'netAmount',
                            text: 'Betrag'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'status',
                            text: 'Status'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'size',
                            text: 'Positionen'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'BestellungDataStore'
                        },
                        {
                            xtype: 'toolbar',
                            items: [{
                                id: 'ErstelleBestellungButton',
                                icon: 'images/add.png',
                                text: 'erstelle',
                                scope: this
                            }, {
                                id: 'AbBestellungButton',
                                text: 'Auftrag best&auml;tigen',
                                icon:'images/new_ab.png',
                                tooltip: 'Auftrag bestaetigen. Damit kommen die Bestellpositionen unter offene Posten',
                                disabled: true,
                                schope:this
                            },{
                                id: 'RechnungBestellungButton',
                                text: 'Rechnung erstellen',
                                icon:'images/new_rechnung.png',
                                tooltip: 'Rechnung in Pdf erstellen und aus den offenen Posten herausnehmen.',
                                disabled: true,
                                schope:this
                            },{
                                id: 'BezahltBestellungButton',
                                text: 'Als Bezahlt markieren',
                                icon:'images/bezahlt.png',
                                tooltip: 'Bestellung als bezahlt markieren',
                                disabled: true,
                                schope:this
                            }, {
                                id: 'StornoBestellungButton',
                                icon: 'images/delete_task.png',
                                text: 'stornieren',
                                tooltip: 'Die Bestellung bleibt in der Datenbank, wird allerdings als "Storniert" markiert',
                                disabled: true,
                                scope: this
                            }, {
                                id: 'DeleteBestellungButton',
                                icon: 'images/delete.png',
                                text: 'l&ouml;schen',
                                tooltip: 'Bestellung wird engdg&uuml;ltig aus der Datenbank gel&ouml;scht.',
                                disabled: true,
                                scope: this
                            },{
                                xtype: 'tbseparator'
                            },  {
                                xtype: 'button',
                                text: 'PDF',
                                icon: 'images/pdf_button.png',
                                menu: {
                                    xtype: 'menu',
                                    minWidth: 120,
                                    items: [
                                        {
                                            id: 'BestellungPdf',
                                            xtype: 'menuitem',
                                            text: 'Bestellung',
                                            disabled: true
                                        },
                                        {
                                            id: 'AbPdf',
                                            xtype: 'menuitem',
                                            text: 'Auftragsbest&auml;tigung',
                                            disabled: true
                                        },
                                        {
                                            id: 'RechnungPdf',
                                            xtype: 'menuitem',
                                            text: 'Rechnung',
                                            disabled: true
                                        },
                                        {
                                            xtype: 'menuseparator'
                                        },{
                                            id: 'OffeneBpPdf',
                                            xtype: 'menuitem',
                                            text: 'Offene Bestellpositionen',
                                            disabled: true
                                        }]
                                    }
                            }]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    id: 'BestellpositionGridPanel',
                    title: 'Bestellpositionen',
                    store: 'BestellpositionDataStore',
                    viewConfig: {
                        id: 'BestellpositionGrid'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'artikel',
                            text: 'Artikel',
                            editor: {
                                id: 'ArtikelComboBox',
                                width: 150,
                                xtype: 'combobox',
                                //allowBlank: false,
                                displayField: 'name',
                                enableRegEx: true,
                                forceSelection: true,
                                queryMode: 'local',
                                store: 'ArtikelDataStore',
                                tpl: Ext.create('Ext.XTemplate',
                                    '<tpl for=".">',
                                    '<div class="x-boundlist-item">{artikelnummer} - {name}</div>',
                                    '</tpl>'
                                ),
                                displayTpl: Ext.create('Ext.XTemplate',
                                    '<tpl for=".">',
                                    '{artikelnummer} - {name}',
                                    '</tpl>'
                                )
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'bestellung',
                            width: 50,
                            text: 'Bestellung'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'rechnung',
                            width: 50,
                            text: 'Rechnung'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'auftragsbestaetigung',
                            width: 50,
                            text: 'AB'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'menge',
                            width: 50,
                            text: 'Menge'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'preisNetto',
                            width: 50,
                            text: 'Preis Netto'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'status',
                            width: 50,
                            text: 'Status'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'geteilt',
                            width: 50,
                            text: 'Geteilt'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'anNaeherei',
                            text: 'AnNaeherei'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'auslieferungsdatum',
                            text: 'ausgeliefert',
                            width: 50
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'geplantAusliefdatum',
                            text: 'Gepl.',
                            width: 50,
                            editor: {
                                xtype: 'datefield',
                                format: 'd/m/Y',
                                allowBlank: true,
                                minValue: Ext.Date.format(new Date(), 'd/m/Y'),
                                minText: 'Datum liegt in der Vergangenheit'
                            }
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            items: [{
                                id: 'ErstelleBpButton',
                                icon: 'images/add.png',
                                text: 'hinzuf&uuml;gen',
                                scope: this
                            }, {
                                id: 'DeleteBpButton',
                                icon: 'images/delete.png',
                                text: 'l&ouml;schen',
                                disabled: true,
                                scope: this
                            }]
                        }
                    ]/*,
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {
                            id: 'BpGridRowEditing',
                            clicksToMoveEditor: 1,
                            autoCancel: false
                        })
                    ]*/
                }
            ]
        });
        me.callParent(arguments);
    }
});