// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.switajski.priebes.flexibleorders.domain;

import de.switajski.priebes.flexibleorders.domain.ArchiveItem;
import javax.persistence.Entity;

privileged aspect ArchiveItem_Roo_Jpa_Entity {
    
    declare @type: ArchiveItem: @Entity;
    
}
