// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.switajski.priebes.flexibleorders.domain;

import de.switajski.priebes.flexibleorders.domain.ArchiveItem;
import de.switajski.priebes.flexibleorders.domain.ArchiveItemDataOnDemand;
import de.switajski.priebes.flexibleorders.domain.Customer;
import de.switajski.priebes.flexibleorders.domain.CustomerDataOnDemand;
import de.switajski.priebes.flexibleorders.domain.Product;
import de.switajski.priebes.flexibleorders.domain.ProductDataOnDemand;
import de.switajski.priebes.flexibleorders.reference.Country;
import de.switajski.priebes.flexibleorders.reference.Status;
import de.switajski.priebes.flexibleorders.repository.ArchiveItemRepository;
import de.switajski.priebes.flexibleorders.service.ArchiveItemService;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ArchiveItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ArchiveItemDataOnDemand: @Component;
    
    private Random ArchiveItemDataOnDemand.rnd = new SecureRandom();
    
    private List<ArchiveItem> ArchiveItemDataOnDemand.data;
    
    @Autowired
    CustomerDataOnDemand ArchiveItemDataOnDemand.customerDataOnDemand;
    
    @Autowired
    ProductDataOnDemand ArchiveItemDataOnDemand.productDataOnDemand;
    
    @Autowired
    ArchiveItemService ArchiveItemDataOnDemand.archiveItemService;
    
    @Autowired
    ArchiveItemRepository ArchiveItemDataOnDemand.archiveItemRepository;
    
    public ArchiveItem ArchiveItemDataOnDemand.getNewTransientArchiveItem(int index) {
        ArchiveItem obj = new ArchiveItem();
        setAccountNumber(obj, index);
        setAnNaeherei(obj, index);
        setCreated(obj, index);
        setCustomer(obj, index);
        setExpectedDelivery(obj, index);
        setInvoiceCity(obj, index);
        setInvoiceCountry(obj, index);
        setInvoiceName1(obj, index);
        setInvoiceName2(obj, index);
        setInvoiceNumber(obj, index);
        setInvoicePostalCode(obj, index);
        setInvoiceStreet(obj, index);
        setOrderConfirmationNumber(obj, index);
        setOrderNumber(obj, index);
        setPriceNet(obj, index);
        setProduct(obj, index);
        setProductName(obj, index);
        setProductNumber(obj, index);
        setQuantity(obj, index);
        setShippingCity(obj, index);
        setShippingCountry(obj, index);
        setShippingName1(obj, index);
        setShippingName2(obj, index);
        setShippingPostalCode(obj, index);
        setShippingStreet(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void ArchiveItemDataOnDemand.setAccountNumber(ArchiveItem obj, int index) {
        Long accountNumber = new Integer(index).longValue();
        obj.setAccountNumber(accountNumber);
    }
    
    public void ArchiveItemDataOnDemand.setAnNaeherei(ArchiveItem obj, int index) {
        Boolean anNaeherei = Boolean.TRUE;
        obj.setAnNaeherei(anNaeherei);
    }
    
    public void ArchiveItemDataOnDemand.setCreated(ArchiveItem obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void ArchiveItemDataOnDemand.setCustomer(ArchiveItem obj, int index) {
        Customer customer = customerDataOnDemand.getRandomCustomer();
        obj.setCustomer(customer);
    }
    
    public void ArchiveItemDataOnDemand.setExpectedDelivery(ArchiveItem obj, int index) {
        Date expectedDelivery = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setExpectedDelivery(expectedDelivery);
    }
    
    public void ArchiveItemDataOnDemand.setInvoiceCity(ArchiveItem obj, int index) {
        String invoiceCity = "invoiceCity_" + index;
        obj.setInvoiceCity(invoiceCity);
    }
    
    public void ArchiveItemDataOnDemand.setInvoiceCountry(ArchiveItem obj, int index) {
        Country invoiceCountry = Country.class.getEnumConstants()[0];
        obj.setInvoiceCountry(invoiceCountry);
    }
    
    public void ArchiveItemDataOnDemand.setInvoiceName1(ArchiveItem obj, int index) {
        String invoiceName1 = "invoiceName1_" + index;
        obj.setInvoiceName1(invoiceName1);
    }
    
    public void ArchiveItemDataOnDemand.setInvoiceName2(ArchiveItem obj, int index) {
        String invoiceName2 = "invoiceName2_" + index;
        obj.setInvoiceName2(invoiceName2);
    }
    
    public void ArchiveItemDataOnDemand.setInvoiceNumber(ArchiveItem obj, int index) {
        Long invoiceNumber = new Integer(index).longValue();
        obj.setInvoiceNumber(invoiceNumber);
    }
    
    public void ArchiveItemDataOnDemand.setInvoicePostalCode(ArchiveItem obj, int index) {
        int invoicePostalCode = index;
        obj.setInvoicePostalCode(invoicePostalCode);
    }
    
    public void ArchiveItemDataOnDemand.setInvoiceStreet(ArchiveItem obj, int index) {
        String invoiceStreet = "invoiceStreet_" + index;
        obj.setInvoiceStreet(invoiceStreet);
    }
    
    public void ArchiveItemDataOnDemand.setOrderConfirmationNumber(ArchiveItem obj, int index) {
        Long orderConfirmationNumber = new Integer(index).longValue();
        obj.setOrderConfirmationNumber(orderConfirmationNumber);
    }
    
    public void ArchiveItemDataOnDemand.setOrderNumber(ArchiveItem obj, int index) {
        Long orderNumber = new Integer(index).longValue();
        obj.setOrderNumber(orderNumber);
    }
    
    public void ArchiveItemDataOnDemand.setPriceNet(ArchiveItem obj, int index) {
        BigDecimal priceNet = BigDecimal.valueOf(index);
        obj.setPriceNet(priceNet);
    }
    
    public void ArchiveItemDataOnDemand.setProduct(ArchiveItem obj, int index) {
        Product product = productDataOnDemand.getSpecificProduct(index);
        obj.setProduct(product);
    }
    
    public void ArchiveItemDataOnDemand.setProductName(ArchiveItem obj, int index) {
        String productName = "productName_" + index;
        obj.setProductName(productName);
    }
    
    public void ArchiveItemDataOnDemand.setProductNumber(ArchiveItem obj, int index) {
        Long productNumber = new Integer(index).longValue();
        obj.setProductNumber(productNumber);
    }
    
    public void ArchiveItemDataOnDemand.setQuantity(ArchiveItem obj, int index) {
        int quantity = index;
        obj.setQuantity(quantity);
    }
    
    public void ArchiveItemDataOnDemand.setShippingCity(ArchiveItem obj, int index) {
        String shippingCity = "shippingCity_" + index;
        obj.setShippingCity(shippingCity);
    }
    
    public void ArchiveItemDataOnDemand.setShippingCountry(ArchiveItem obj, int index) {
        Country shippingCountry = Country.class.getEnumConstants()[0];
        obj.setShippingCountry(shippingCountry);
    }
    
    public void ArchiveItemDataOnDemand.setShippingName1(ArchiveItem obj, int index) {
        String shippingName1 = "shippingName1_" + index;
        obj.setShippingName1(shippingName1);
    }
    
    public void ArchiveItemDataOnDemand.setShippingName2(ArchiveItem obj, int index) {
        String shippingName2 = "shippingName2_" + index;
        obj.setShippingName2(shippingName2);
    }
    
    public void ArchiveItemDataOnDemand.setShippingPostalCode(ArchiveItem obj, int index) {
        int shippingPostalCode = index;
        obj.setShippingPostalCode(shippingPostalCode);
    }
    
    public void ArchiveItemDataOnDemand.setShippingStreet(ArchiveItem obj, int index) {
        String shippingStreet = "shippingStreet_" + index;
        obj.setShippingStreet(shippingStreet);
    }
    
    public void ArchiveItemDataOnDemand.setStatus(ArchiveItem obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public ArchiveItem ArchiveItemDataOnDemand.getSpecificArchiveItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ArchiveItem obj = data.get(index);
        Long id = obj.getId();
        return archiveItemService.findArchiveItem(id);
    }
    
    public ArchiveItem ArchiveItemDataOnDemand.getRandomArchiveItem() {
        init();
        ArchiveItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return archiveItemService.findArchiveItem(id);
    }
    
    public boolean ArchiveItemDataOnDemand.modifyArchiveItem(ArchiveItem obj) {
        return false;
    }
    
    public void ArchiveItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = archiveItemService.findArchiveItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ArchiveItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ArchiveItem>();
        for (int i = 0; i < 10; i++) {
            ArchiveItem obj = getNewTransientArchiveItem(i);
            try {
                archiveItemService.saveArchiveItem(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            archiveItemRepository.flush();
            data.add(obj);
        }
    }
    
}
