// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.switajski.priebes.flexibleorders.domain;

import de.switajski.priebes.flexibleorders.domain.Category;
import de.switajski.priebes.flexibleorders.domain.CategoryDataOnDemand;
import de.switajski.priebes.flexibleorders.repository.CategoryRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoryDataOnDemand: @Component;
    
    private Random CategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Category> CategoryDataOnDemand.data;
    
    @Autowired
    CategoryRepository CategoryDataOnDemand.categoryRepository;
    
    public Category CategoryDataOnDemand.getNewTransientCategory(int index) {
        Category obj = new Category();
        setActivated(obj, index);
        setDescription(obj, index);
        setImage(obj, index);
        setImageGalery(obj, index);
        setIntro(obj, index);
        setName(obj, index);
        setSortOrder(obj, index);
        return obj;
    }
    
    public void CategoryDataOnDemand.setActivated(Category obj, int index) {
        Boolean activated = Boolean.TRUE;
        obj.setActivated(activated);
    }
    
    public void CategoryDataOnDemand.setDescription(Category obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void CategoryDataOnDemand.setImage(Category obj, int index) {
        String image = "image_" + index;
        obj.setImage(image);
    }
    
    public void CategoryDataOnDemand.setImageGalery(Category obj, int index) {
        String imageGalery = "imageGalery_" + index;
        obj.setImageGalery(imageGalery);
    }
    
    public void CategoryDataOnDemand.setIntro(Category obj, int index) {
        String intro = "intro_" + index;
        obj.setIntro(intro);
    }
    
    public void CategoryDataOnDemand.setName(Category obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void CategoryDataOnDemand.setSortOrder(Category obj, int index) {
        int sortOrder = index;
        obj.setSortOrder(sortOrder);
    }
    
    public Category CategoryDataOnDemand.getSpecificCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Category obj = data.get(index);
        Long id = obj.getId();
        return categoryRepository.findOne(id);
    }
    
    public Category CategoryDataOnDemand.getRandomCategory() {
        init();
        Category obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return categoryRepository.findOne(id);
    }
    
    public boolean CategoryDataOnDemand.modifyCategory(Category obj) {
        return false;
    }
    
    public void CategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = categoryRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Category' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Category>();
        for (int i = 0; i < 10; i++) {
            Category obj = getNewTransientCategory(i);
            try {
                categoryRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            categoryRepository.flush();
            data.add(obj);
        }
    }
    
}
