// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.switajski.priebes.flexibleorders.domain;

import de.switajski.priebes.flexibleorders.domain.CustomerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomerDataOnDemand_Roo_Configurable {
    
    declare @type: CustomerDataOnDemand: @Configurable;
    
}
