// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.switajski.priebes.flexibleorders.domain;

import de.switajski.priebes.flexibleorders.domain.Customer;
import de.switajski.priebes.flexibleorders.domain.CustomerDataOnDemand;
import de.switajski.priebes.flexibleorders.domain.Product;
import de.switajski.priebes.flexibleorders.domain.ProductDataOnDemand;
import de.switajski.priebes.flexibleorders.domain.ShippingItem;
import de.switajski.priebes.flexibleorders.domain.ShippingItemDataOnDemand;
import de.switajski.priebes.flexibleorders.reference.Country;
import de.switajski.priebes.flexibleorders.repository.ShippingItemRepository;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ShippingItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ShippingItemDataOnDemand: @Component;
    
    private Random ShippingItemDataOnDemand.rnd = new SecureRandom();
    
    private List<ShippingItem> ShippingItemDataOnDemand.data;
    
    @Autowired
    CustomerDataOnDemand ShippingItemDataOnDemand.customerDataOnDemand;
    
    @Autowired
    ProductDataOnDemand ShippingItemDataOnDemand.productDataOnDemand;
    
    @Autowired
    ShippingItemRepository ShippingItemDataOnDemand.shippingItemRepository;
    
    public ShippingItem ShippingItemDataOnDemand.getNewTransientShippingItem(int index) {
        ShippingItem obj = new ShippingItem();
        setAccountNumber(obj, index);
        setCreated(obj, index);
        setCustomer(obj, index);
        setExpectedDelivery(obj, index);
        setInvoiceNumber(obj, index);
        setOrderConfirmationNumber(obj, index);
        setOrderNumber(obj, index);
        setPriceNet(obj, index);
        setProduct(obj, index);
        setProductName(obj, index);
        setProductNumber(obj, index);
        setQuantity(obj, index);
        setQuantityLeft(obj, index);
        setShippingCity(obj, index);
        setShippingCountry(obj, index);
        setShippingName1(obj, index);
        setShippingName2(obj, index);
        setShippingPostalCode(obj, index);
        setShippingStreet(obj, index);
        setTransmitToSupplier(obj, index);
        return obj;
    }
    
    public void ShippingItemDataOnDemand.setAccountNumber(ShippingItem obj, int index) {
        Long accountNumber = new Integer(index).longValue();
        obj.setAccountNumber(accountNumber);
    }
    
    public void ShippingItemDataOnDemand.setCreated(ShippingItem obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void ShippingItemDataOnDemand.setCustomer(ShippingItem obj, int index) {
        Customer customer = customerDataOnDemand.getRandomCustomer();
        obj.setCustomer(customer);
    }
    
    public void ShippingItemDataOnDemand.setExpectedDelivery(ShippingItem obj, int index) {
        Date expectedDelivery = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setExpectedDelivery(expectedDelivery);
    }
    
    public void ShippingItemDataOnDemand.setInvoiceNumber(ShippingItem obj, int index) {
        Long invoiceNumber = new Integer(index).longValue();
        obj.setInvoiceNumber(invoiceNumber);
    }
    
    public void ShippingItemDataOnDemand.setOrderConfirmationNumber(ShippingItem obj, int index) {
        Long orderConfirmationNumber = new Integer(index).longValue();
        obj.setOrderConfirmationNumber(orderConfirmationNumber);
    }
    
    public void ShippingItemDataOnDemand.setOrderNumber(ShippingItem obj, int index) {
        Long orderNumber = new Integer(index).longValue();
        obj.setOrderNumber(orderNumber);
    }
    
    public void ShippingItemDataOnDemand.setPriceNet(ShippingItem obj, int index) {
        BigDecimal priceNet = BigDecimal.valueOf(index);
        obj.setPriceNet(priceNet);
    }
    
    public void ShippingItemDataOnDemand.setProduct(ShippingItem obj, int index) {
        Product product = productDataOnDemand.getSpecificProduct(index);
        obj.setProduct(product);
    }
    
    public void ShippingItemDataOnDemand.setProductName(ShippingItem obj, int index) {
        String productName = "productName_" + index;
        obj.setProductName(productName);
    }
    
    public void ShippingItemDataOnDemand.setProductNumber(ShippingItem obj, int index) {
        Long productNumber = new Integer(index).longValue();
        obj.setProductNumber(productNumber);
    }
    
    public void ShippingItemDataOnDemand.setQuantity(ShippingItem obj, int index) {
        int quantity = index;
        obj.setQuantity(quantity);
    }
    
    public void ShippingItemDataOnDemand.setQuantityLeft(ShippingItem obj, int index) {
        Integer quantityLeft = new Integer(index);
        obj.setQuantityLeft(quantityLeft);
    }
    
    public void ShippingItemDataOnDemand.setShippingCity(ShippingItem obj, int index) {
        String shippingCity = "shippingCity_" + index;
        obj.setShippingCity(shippingCity);
    }
    
    public void ShippingItemDataOnDemand.setShippingCountry(ShippingItem obj, int index) {
        Country shippingCountry = Country.class.getEnumConstants()[0];
        obj.setShippingCountry(shippingCountry);
    }
    
    public void ShippingItemDataOnDemand.setShippingName1(ShippingItem obj, int index) {
        String shippingName1 = "shippingName1_" + index;
        obj.setShippingName1(shippingName1);
    }
    
    public void ShippingItemDataOnDemand.setShippingName2(ShippingItem obj, int index) {
        String shippingName2 = "shippingName2_" + index;
        obj.setShippingName2(shippingName2);
    }
    
    public void ShippingItemDataOnDemand.setShippingPostalCode(ShippingItem obj, int index) {
        int shippingPostalCode = index;
        obj.setShippingPostalCode(shippingPostalCode);
    }
    
    public void ShippingItemDataOnDemand.setShippingStreet(ShippingItem obj, int index) {
        String shippingStreet = "shippingStreet_" + index;
        obj.setShippingStreet(shippingStreet);
    }
    
    public void ShippingItemDataOnDemand.setTransmitToSupplier(ShippingItem obj, int index) {
        Boolean transmitToSupplier = Boolean.TRUE;
        obj.setTransmitToSupplier(transmitToSupplier);
    }
    
    public ShippingItem ShippingItemDataOnDemand.getSpecificShippingItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ShippingItem obj = data.get(index);
        Long id = obj.getId();
        return shippingItemRepository.findOne(id);
    }
    
    public ShippingItem ShippingItemDataOnDemand.getRandomShippingItem() {
        init();
        ShippingItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return shippingItemRepository.findOne(id);
    }
    
    public boolean ShippingItemDataOnDemand.modifyShippingItem(ShippingItem obj) {
        return false;
    }
    
    public void ShippingItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = shippingItemRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ShippingItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ShippingItem>();
        for (int i = 0; i < 10; i++) {
            ShippingItem obj = getNewTransientShippingItem(i);
            try {
                shippingItemRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            shippingItemRepository.flush();
            data.add(obj);
        }
    }
    
}
