/*
 * File: app/model/BestellpositionData.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.BestellpositionData', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'artikel',
            type: 'int'
        },
        {
            //TODO: Testen, ob die Bestellung im JSON ohne Anführungszeichen kommt
            name: 'bestellung',
            type: 'int'
        },
        {
            name: 'rechnung'
        },
        {
            name: 'auftragsbestaetigung'
        },
        {
            name: 'menge',
            type: 'int'
        },
        {
            name: 'preisNetto'
        },
        {
            name: 'status'
        },
        {
            name: 'geteilt',
            type: 'boolean',
            defaultValue: {
                booleanValue: false
            }
        },
        {
            name: 'anNaeherei',
            type: 'boolean',
            defaultValue: {
                booleanValue: false
            }
        },
        {
            name: 'auslieferungsdatum'
        },
        {
            name: 'geplantAusliefdatum'
        }
    ]
});