/*
 * File: app/model/KundeData.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.KundeData', {
    extend: 'Ext.data.Model',

    idProperty: 'kundenummer',

    fields: [
        {
            name: 'kundennummer'
        },
        {
            name: 'anrede'
        },
        {
            name: 'vorname'
        },
        {
            name: 'nachname'
        },
        {
            name: 'email'
        },
        {
            name: 'telefon'
        },
        {
            name: 'mobil'
        },
        {
            name: 'firma'
        },
        {
            name: 'benutzerkonto'
        },
        {
            name: 'kundenart'
        },
        {
            name: 'erstelltDatum'
        },
        {
            name: 'bild'
        },
        {
            name: 'eigeneHinweise'
        },
        {
            name: 'rabattprozent'
        },
        {
            name: 'rechnungsadresse'
        },
        {
            name: 'lieferadresse'
        }
    ]
});