/*
 * File: app/model/KundeData.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.KundeData', {
    extend: 'Ext.data.Model',

    idProperty: 'id',

    fields: [
        {
            name: 'customerNumber'
        },
        {
            name: 'firstName'
        },
        {
            name: 'lastName'
        },
        {
            name: 'email'
        },
        {
            name: 'phone'
        },
        {
            name: 'name1'
        },
        {
            name: 'name2'
        },
        {
            name: 'street'
        },
        {
            name: 'postalCode'
        },
        {
            name: 'city'
        },
        {
            name: 'country'
        },
        {
            name: 'paymentConditions'
        },
        {
            name: 'vatIdNo'
        },
        {
            name: 'vendorNumber'
        },
        //TODO: make address a child data structure
        {
            name: 'dname1'
        },
        {
            name: 'dname2'
        },
        {
            name: 'dstreet'
        },
        {
            name: 'dpostalCode'
        },
        {
            name: 'dcity'
        },
        {
            name: 'dcountry'
        }
     ]
});