// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.switajski.priebes.flexibleorders.importer;

import de.switajski.priebes.flexibleorders.importer.PriebesJoomlaImporterServiceTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PriebesJoomlaImporterServiceTest_Roo_Configurable {
    
    declare @type: PriebesJoomlaImporterServiceTest: @Configurable;
    
}
